Update patch set 1
Patch Set 1:

I guess I assumed this would work in aosp10 and merged too hastily:

FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: system/core/init/Android.bp:60:16: unrecognized property "product_variables.omnirom"
17:07:26 soong bootstrap failed with: exit status 1

Is this fixable? Otherwise this might need to be on an omni only project for this repository.

Patch-set: 1